name: smartpost_ai
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  loader_overlay: ^4.0.3
  flutter_svg: ^2.0.16
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.3.2
  package_info_plus: ^8.1.1
  logger: ^2.5.0
  firebase_auth: ^5.3.4
  material_dialogs: ^1.1.5
  flutter_gemini: ^3.0.0
  http: ^1.2.2
  simple_chips_input: ^1.2.0
  share_plus: ^10.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  device_info_plus: ^11.2.0
  image: ^4.0.15
  google_generative_ai: ^0.4.7



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  generate: true

  uses-material-design: true

#  assets:
#    - assets/default_assets/
#    - assets/images/